/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuctionContract } from "./AuctionContract";
export type { Lottery } from "./Lottery";
export type { LotteryToken } from "./LotteryToken";
export type { NFTContract } from "./NFTContract";
