/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  NotQuiteRandom,
  NotQuiteRandomInterface,
} from "../../contracts/NotQuiteRandom";

const _abi = [
  {
    inputs: [],
    name: "getRandomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "notQuiteRandomNumber",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tossCoin",
    outputs: [
      {
        internalType: "bool",
        name: "heads",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610197806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063b41e8cad1461003b578063dbdff2c114610059575b600080fd5b610043610077565b60405161005091906100af565b60405180910390f35b61006161007c565b60405161006e91906100e3565b60405180910390f35b600090565b600060014361008b919061012d565b4060001c905090565b60008115159050919050565b6100a981610094565b82525050565b60006020820190506100c460008301846100a0565b92915050565b6000819050919050565b6100dd816100ca565b82525050565b60006020820190506100f860008301846100d4565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b6000610138826100ca565b9150610143836100ca565b925082820390508181111561015b5761015a6100fe565b5b9291505056fea2646970667358221220b890f4a8872c9df15cdede928cce2287f9c105ebaf38cafa28348cf2b1b9bb6664736f6c63430008130033";

type NotQuiteRandomConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NotQuiteRandomConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NotQuiteRandom__factory extends ContractFactory {
  constructor(...args: NotQuiteRandomConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      NotQuiteRandom & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): NotQuiteRandom__factory {
    return super.connect(runner) as NotQuiteRandom__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NotQuiteRandomInterface {
    return new Interface(_abi) as NotQuiteRandomInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NotQuiteRandom {
    return new Contract(address, _abi, runner) as unknown as NotQuiteRandom;
  }
}
