/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Random, RandomInterface } from "../../contracts/Random";

const _abi = [
  {
    inputs: [],
    name: "getRandomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "randomNumber",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tossCoin",
    outputs: [
      {
        internalType: "bool",
        name: "heads",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061019c806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063b41e8cad1461003b578063dbdff2c114610059575b600080fd5b610043610077565b60405161005091906100b7565b60405180910390f35b610061610094565b60405161006e91906100eb565b60405180910390f35b6000806002610084610094565b61008e9190610135565b14905090565b600044905090565b60008115159050919050565b6100b18161009c565b82525050565b60006020820190506100cc60008301846100a8565b92915050565b6000819050919050565b6100e5816100d2565b82525050565b600060208201905061010060008301846100dc565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b6000610140826100d2565b915061014b836100d2565b92508261015b5761015a610106565b5b82820690509291505056fea264697066735822122050db831dea3ff02bba7b7d74714ee8a5211c78236528c69f2d40add4d90a298364736f6c63430008130033";

type RandomConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RandomConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Random__factory extends ContractFactory {
  constructor(...args: RandomConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Random & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Random__factory {
    return super.connect(runner) as Random__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RandomInterface {
    return new Interface(_abi) as RandomInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Random {
    return new Contract(address, _abi, runner) as unknown as Random;
  }
}
